name: Tests

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Run benchmark tests
        run: python -m unittest -v tests/test_benchmark.py
        env:
          PYTHONPATH: src
